repo_url: https://github.com/SBD1/2024.2-Castlevania
repo_name: 2024.2-Castlevania
site_url: https://github.com/SBD1/2024.2-Castlevania

site_name: Castlevania
nav:
  - Inicio: "index.md"
  - Apresentações:
    - Apresentação 1: "apresentacao/modulo1.md"
    - Apresentação 2: "apresentacao/modulo2.md"
  - Entrega 1:
    - Diagrama Entidade Relacionamento: "modulo1/der.md"
    - Modelo Entidade Relacionamento: "modulo1/mer.md"
    - Dicionário de Dados: "modulo1/dd.md"
    - Modelo Relacional: "modulo1/mr.md"
  - Entrega 2:
    - Normalização: "modulo2/norm.md"
    - Data Definition Language: "modulo2/ddl.md"
    - Data Manipulation Language: "modulo2/dml.md"
    - Data Query Language: "modulo2/dql.md"
    - Algebra Relacional: "modulo2/algebra_relacional.md"
    - Terminal: "modulo2/terminal.md"
  - Entrega 3: 
    - Triggers: "modulo3/triggers.md"
    - Procedures: "modulo3/procedimentos.md"
    - O Jogo: "modulo3/jogo.md"

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: orange
