repo_url: https://github.com/SBD1/2024.2-Castlevania
repo_name: 2024.2-Castlevania
site_url: https://github.com/SBD1/2024.2-Castlevania

site_name: Castlevania
nav:
  - Inicio: "index.md"

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: orange
